import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/auth-context";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "./contexts/cart-context";
import { CategoryProvider } from "./contexts/category-context";
import { ProductProvider } from "./contexts/product-context";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   weight: ["400", "500", "600", "700"], 
//   subsets: ["latin"],
//   variable: "--font-poppins",
// });

export const metadata: Metadata = {
  title: "Food Bundles",
  description: "Generated by Sostene, Elie, Shyirambere",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body suppressHydrationWarning>
        <AuthProvider>
          <ProductProvider>
            <CartProvider>
              <CategoryProvider>{children}</CategoryProvider>
            </CartProvider>
          </ProductProvider>
        </AuthProvider>
        <ToastContainer />
        <Toaster />
      </body>
    </html>
  );
}
