import type {
  MINAGRIBenchmarkRecord,
  RecipeItem,
  IngredientSubstitution,
  PriceForecastItem,
  DemandForecastItem,
  SmartRecommendation,
  AnomalyRecord,
  FarmerDemandSignal,
  SupplierQualityScore,
  TraceabilityBatch,
  MarketReport,
} from "@/types/minagri-intelligence";

export const MOCK_MINAGRI_BENCHMARKS: MINAGRIBenchmarkRecord[] = [
  {
    id: "m-1",
    productId: "p-tomatoes",
    productName: "Tomatoes (Plum)",
    category: "Vegetables",
    unit: "kg",
    marketName: "Kimironko Market",
    region: "Kigali",
    minagriReferencePrice: 1350,
    platformPrice: 1200,
    traderAvgPrice: 1400,
    recordedDate: "2026-09-10",
    lastUpdatedTime: "10:30 AM Today",
    freshnessStatus: "Fresh Today",
    priceChange30d: 8.5,
    volatility: "High",
    confidenceScore: 96,
  },
  {
    id: "m-2",
    productId: "p-potatoes",
    productName: "Irish Potatoes (Kinigi)",
    category: "Roots & Tubers",
    unit: "kg",
    marketName: "Musanze Central Market",
    region: "Northern",
    minagriReferencePrice: 520,
    platformPrice: 480,
    traderAvgPrice: 550,
    recordedDate: "2026-09-10",
    lastUpdatedTime: "08:15 AM Today",
    freshnessStatus: "Fresh Today",
    priceChange30d: -4.2,
    volatility: "Stable",
    confidenceScore: 98,
  },
  {
    id: "m-3",
    productId: "p-beef",
    productName: "Prime Fresh Beef",
    category: "Meat & Poultry",
    unit: "kg",
    marketName: "Nyabugogo Slaughterhouse",
    region: "Kigali",
    minagriReferencePrice: 4800,
    platformPrice: 4500,
    traderAvgPrice: 4950,
    recordedDate: "2026-09-09",
    lastUpdatedTime: "Yesterday",
    freshnessStatus: "1 Day Ago",
    priceChange30d: 3.1,
    volatility: "Moderate",
    confidenceScore: 92,
  },
  {
    id: "m-4",
    productId: "p-chicken",
    productName: "Whole Local Chicken",
    category: "Meat & Poultry",
    unit: "kg",
    marketName: "Kicukiro Market",
    region: "Kigali",
    minagriReferencePrice: 3950,
    platformPrice: 3800,
    traderAvgPrice: 4100,
    recordedDate: "2026-09-10",
    lastUpdatedTime: "09:45 AM Today",
    freshnessStatus: "Fresh Today",
    priceChange30d: -2.8,
    volatility: "Stable",
    confidenceScore: 94,
  },
  {
    id: "m-5",
    productId: "p-onions",
    productName: "Red Onions",
    category: "Vegetables",
    unit: "kg",
    marketName: "Rwamagana Market",
    region: "Eastern",
    minagriReferencePrice: 980,
    platformPrice: 900,
    traderAvgPrice: 1020,
    recordedDate: "2026-09-10",
    lastUpdatedTime: "11:00 AM Today",
    freshnessStatus: "Fresh Today",
    priceChange30d: 14.2,
    volatility: "Extreme",
    confidenceScore: 91,
  },
  {
    id: "m-6",
    productId: "p-rice",
    productName: "Long Grain White Rice",
    category: "Grains",
    unit: "kg",
    marketName: "Bugarama / Rusizi Market",
    region: "Western",
    minagriReferencePrice: 1100,
    platformPrice: 1000,
    traderAvgPrice: 1150,
    recordedDate: "2026-09-08",
    lastUpdatedTime: "2 Days Ago",
    freshnessStatus: "2 Days Ago",
    priceChange30d: 0.0,
    volatility: "Stable",
    confidenceScore: 89,
  },
  {
    id: "m-7",
    productId: "p-oil",
    productName: "Refined Cooking Oil",
    category: "Oils & Fats",
    unit: "L",
    marketName: "Kigali Central Wholesale",
    region: "Kigali",
    minagriReferencePrice: 2800,
    platformPrice: 2500,
    traderAvgPrice: 2900,
    recordedDate: "2026-09-10",
    lastUpdatedTime: "07:30 AM Today",
    freshnessStatus: "Fresh Today",
    priceChange30d: 18.6,
    volatility: "High",
    confidenceScore: 95,
  },
];

export const MOCK_RESTAURANT_RECIPES: RecipeItem[] = [
  {
    id: "r-1",
    dishName: "Signature Beef Stew & Kinigi Fries",
    category: "Main Course",
    sellingPrice: 7500,
    targetFoodCostPct: 32,
    foodCostPct: 38.4,
    totalIngredientCost: 2880,
    grossMarginRwf: 4620,
    grossMarginPct: 61.6,
    volatilityLevel: "High",
    opportunityScore: 78,
    substitutionsAvailable: 2,
    statusAlert: "OVER_COST_TARGET",
    ingredients: [
      { id: "i-1", ingredientName: "Prime Fresh Beef", quantity: 0.35, unit: "kg", currentUnitPrice: 4500, historicalUnitPrice: 4100, itemCost: 1575 },
      { id: "i-2", ingredientName: "Irish Potatoes (Kinigi)", quantity: 0.4, unit: "kg", currentUnitPrice: 480, historicalUnitPrice: 500, itemCost: 192 },
      { id: "i-3", ingredientName: "Tomatoes (Plum)", quantity: 0.2, unit: "kg", currentUnitPrice: 1200, historicalUnitPrice: 950, itemCost: 240 },
      { id: "i-4", ingredientName: "Red Onions", quantity: 0.1, unit: "kg", currentUnitPrice: 900, historicalUnitPrice: 750, itemCost: 90 },
      { id: "i-5", ingredientName: "Refined Cooking Oil", quantity: 0.15, unit: "L", currentUnitPrice: 2500, historicalUnitPrice: 2100, itemCost: 375 },
      { id: "i-6", ingredientName: "Spices & Herbs", quantity: 1, unit: "portion", currentUnitPrice: 408, historicalUnitPrice: 400, itemCost: 408 },
    ],
  },
  {
    id: "r-2",
    dishName: "Farm-Fresh Grilled Chicken Breast",
    category: "Main Course",
    sellingPrice: 8500,
    targetFoodCostPct: 30,
    foodCostPct: 27.8,
    totalIngredientCost: 2360,
    grossMarginRwf: 6140,
    grossMarginPct: 72.2,
    volatilityLevel: "Stable",
    opportunityScore: 94,
    substitutionsAvailable: 1,
    statusAlert: "OPTIMAL",
    ingredients: [
      { id: "i-7", ingredientName: "Whole Local Chicken (Boneless)", quantity: 0.4, unit: "kg", currentUnitPrice: 3800, historicalUnitPrice: 3900, itemCost: 1520 },
      { id: "i-8", ingredientName: "Fresh Garden Salad", quantity: 0.2, unit: "kg", currentUnitPrice: 1500, historicalUnitPrice: 1600, itemCost: 300 },
      { id: "i-9", ingredientName: "Refined Cooking Oil & Butter", quantity: 0.08, unit: "L", currentUnitPrice: 2500, historicalUnitPrice: 2500, itemCost: 200 },
      { id: "i-10", ingredientName: "Marinade & Seasonings", quantity: 1, unit: "portion", currentUnitPrice: 340, historicalUnitPrice: 340, itemCost: 340 },
    ],
  },
  {
    id: "r-3",
    dishName: "Rich Tomato & Basil Pasta",
    category: "Pasta & Vegetarian",
    sellingPrice: 5500,
    targetFoodCostPct: 28,
    foodCostPct: 34.2,
    totalIngredientCost: 1880,
    grossMarginRwf: 3620,
    grossMarginPct: 65.8,
    volatilityLevel: "Extreme",
    opportunityScore: 65,
    substitutionsAvailable: 3,
    statusAlert: "HIGH_VOLATILITY",
    ingredients: [
      { id: "i-11", ingredientName: "Tomatoes (Plum)", quantity: 0.45, unit: "kg", currentUnitPrice: 1200, historicalUnitPrice: 900, itemCost: 540 },
      { id: "i-12", ingredientName: "Red Onions", quantity: 0.15, unit: "kg", currentUnitPrice: 900, historicalUnitPrice: 700, itemCost: 135 },
      { id: "i-13", ingredientName: "Penne Pasta", quantity: 0.25, unit: "kg", currentUnitPrice: 2800, historicalUnitPrice: 2600, itemCost: 700 },
      { id: "i-14", ingredientName: "Olive Oil & Garlic", quantity: 0.05, unit: "L", currentUnitPrice: 6500, historicalUnitPrice: 6000, itemCost: 325 },
      { id: "i-15", ingredientName: "Fresh Basil", quantity: 0.05, unit: "bunch", currentUnitPrice: 360, historicalUnitPrice: 300, itemCost: 180 },
    ],
  },
  {
    id: "r-4",
    dishName: "Traditional Rwanda Beans & Organic Rice Bowl",
    category: "Vegetarian",
    sellingPrice: 4200,
    targetFoodCostPct: 25,
    foodCostPct: 21.4,
    totalIngredientCost: 900,
    grossMarginRwf: 3300,
    grossMarginPct: 78.6,
    volatilityLevel: "Stable",
    opportunityScore: 98,
    substitutionsAvailable: 1,
    statusAlert: "OPTIMAL",
    ingredients: [
      { id: "i-16", ingredientName: "Yellow Beans", quantity: 0.3, unit: "kg", currentUnitPrice: 900, historicalUnitPrice: 900, itemCost: 270 },
      { id: "i-17", ingredientName: "Long Grain White Rice", quantity: 0.3, unit: "kg", currentUnitPrice: 1000, historicalUnitPrice: 1050, itemCost: 300 },
      { id: "i-18", ingredientName: "Refined Cooking Oil", quantity: 0.05, unit: "L", currentUnitPrice: 2500, historicalUnitPrice: 2500, itemCost: 125 },
      { id: "i-19", ingredientName: "Onions & Tomatoes", quantity: 0.15, unit: "kg", currentUnitPrice: 1100, historicalUnitPrice: 1000, itemCost: 165 },
      { id: "i-20", ingredientName: "Salt & Seasoning", quantity: 1, unit: "portion", currentUnitPrice: 40, historicalUnitPrice: 40, itemCost: 40 },
    ],
  },
];

export const MOCK_SUBSTITUTIONS: IngredientSubstitution[] = [
  {
    id: "sub-1",
    dishId: "r-1",
    dishName: "Signature Beef Stew & Kinigi Fries",
    originalIngredient: "Tomatoes (Plum) [RWF 1,200/kg]",
    originalPrice: 1200,
    proposedIngredient: "Seasonal Musanze Tomato Puree Blend [RWF 850/kg]",
    proposedPrice: 850,
    savingsPct: 29.2,
    qualityMatchPct: 94,
    chefApprovalStatus: "PENDING",
    seasonalityNote: "Musanze harvest peak is yielding surplus puree tomato stock at 29% lower price.",
  },
  {
    id: "sub-2",
    dishId: "r-3",
    dishName: "Rich Tomato & Basil Pasta",
    originalIngredient: "Imported Olive Oil [RWF 6,500/L]",
    originalPrice: 6500,
    proposedIngredient: "Cold-Pressed Rwandan SunOil [RWF 3,800/L]",
    proposedPrice: 3800,
    savingsPct: 41.5,
    qualityMatchPct: 91,
    chefApprovalStatus: "APPROVED",
    seasonalityNote: "Verified locally refined sunflower oil reduces recipe cost by RWF 135/dish.",
  },
];

export const MOCK_PRICE_FORECASTS: PriceForecastItem[] = [
  {
    id: "pf-1",
    productId: "p-tomatoes",
    productName: "Tomatoes (Plum)",
    category: "Vegetables",
    currentPrice: 1200,
    predictedPriceLow: 1050,
    predictedPriceExpected: 1120,
    predictedPriceHigh: 1280,
    horizonDays: 14,
    confidencePct: 88,
    trend: "DOWNWARD",
    primaryDrivers: ["Incoming Musanze & Bugesera harvest", "Favorable weather", "Higher regional market inflows"],
  },
  {
    id: "pf-2",
    productId: "p-beef",
    productName: "Prime Fresh Beef",
    category: "Meat & Poultry",
    currentPrice: 4500,
    predictedPriceLow: 4400,
    predictedPriceExpected: 4750,
    predictedPriceHigh: 5100,
    horizonDays: 30,
    confidencePct: 84,
    trend: "UPWARD",
    primaryDrivers: ["End-of-quarter hospitality demand surge", "Feed transport cost adjustments"],
  },
  {
    id: "pf-3",
    productId: "p-potatoes",
    productName: "Irish Potatoes (Kinigi)",
    category: "Roots & Tubers",
    currentPrice: 480,
    predictedPriceLow: 450,
    predictedPriceExpected: 470,
    predictedPriceHigh: 500,
    horizonDays: 30,
    confidencePct: 95,
    trend: "STABLE",
    primaryDrivers: ["Steady supply from Northern province co-ops", "Consistent platform contract volumes"],
  },
  {
    id: "pf-4",
    productId: "p-oil",
    productName: "Refined Cooking Oil",
    category: "Oils & Fats",
    currentPrice: 2500,
    predictedPriceLow: 2450,
    predictedPriceExpected: 2680,
    predictedPriceHigh: 2900,
    horizonDays: 14,
    confidencePct: 79,
    trend: "UPWARD",
    primaryDrivers: ["Global palm import tariffs", "Port logistics backlog"],
  },
];

export const MOCK_DEMAND_FORECASTS: DemandForecastItem[] = [
  {
    id: "df-1",
    productId: "p-tomatoes",
    productName: "Tomatoes (Plum)",
    category: "Vegetables",
    buyerSegment: "Restaurants",
    currentMonthlyDemandKg: 14500,
    projectedNextMonthDemandKg: 17200,
    growthPct: 18.6,
    seasonalityPeak: "October - November",
    recommendedStockReserveKg: 3500,
  },
  {
    id: "df-2",
    productId: "p-beef",
    productName: "Prime Fresh Beef",
    category: "Meat & Poultry",
    buyerSegment: "Hotels",
    currentMonthlyDemandKg: 8200,
    projectedNextMonthDemandKg: 9600,
    growthPct: 17.0,
    seasonalityPeak: "December Holiday Season",
    recommendedStockReserveKg: 2000,
  },
  {
    id: "df-3",
    productId: "p-potatoes",
    productName: "Irish Potatoes (Kinigi)",
    category: "Roots & Tubers",
    buyerSegment: "Restaurants",
    currentMonthlyDemandKg: 28000,
    projectedNextMonthDemandKg: 31000,
    growthPct: 10.7,
    seasonalityPeak: "All Year",
    recommendedStockReserveKg: 6000,
  },
];

export const MOCK_RECOMMENDATIONS: SmartRecommendation[] = [
  {
    id: "rec-1",
    type: "PROCUREMENT",
    title: "Lock 14-Day Tomato Supply Pre-Contract",
    description: "Tomato prices are projected to drop 7% over 14 days before rebounding ahead of holiday demand.",
    estimatedImpact: "Save est. RWF 145,000 / week on vegetable procurement",
    actionText: "Create Forward Pre-Order",
    confidencePct: 88,
    rationale: "MINAGRI historical time-series shows 88% probability of price recovery post-October week 2.",
    timestamp: "10 mins ago",
  },
  {
    id: "rec-2",
    type: "MENU",
    title: "Promote Kinigi Potato Side Dish Packages",
    description: "Kinigi Potato supplies are at peak regional abundance with 15% lower delivered platform price.",
    estimatedImpact: "Increase restaurant menu margin by +4.2%",
    actionText: "Apply Menu Recipe Tweak",
    confidencePct: 94,
    rationale: "Matching peak local harvest with high POS customer order velocity.",
    timestamp: "1 hour ago",
  },
  {
    id: "rec-3",
    type: "FARMER_PLANTING",
    title: "Issue Red Onion Planting Signal to Musanze & Bugesera Farmers",
    description: "Aggregated restaurant purchasing indicates a 22% demand deficit projected for Q4.",
    estimatedImpact: "Secure 12 Tons guaranteed farmer off-take",
    actionText: "Publish Planting Broadcast",
    confidencePct: 91,
    rationale: "Consolidated anonymized demand across 48 verified Kigali restaurant buyers.",
    timestamp: "3 hours ago",
  },
];

export const MOCK_ANOMALIES: AnomalyRecord[] = [
  {
    id: "anom-1",
    type: "PRICE_SPIKE",
    severity: "critical",
    title: "Unusual +24% Price Spike Detected in Red Onions",
    productName: "Red Onions",
    location: "Rwamagana Market",
    detectedDifference: "RWF 980 -> RWF 1,220 (+24.5%)",
    timestamp: "Today at 08:30 AM",
    status: "OPEN",
    recommendedAction: "Flag trader quotation for human review before updating benchmark rate.",
  },
  {
    id: "anom-2",
    type: "UNUSUAL_QUOTE",
    severity: "warning",
    title: "Outlier Supplier Quote for Cooking Oil",
    productName: "Refined Cooking Oil",
    location: "Nyabugogo Trader C",
    detectedDifference: "Quote of RWF 3,400/L vs MINAGRI Benchmark RWF 2,800/L",
    timestamp: "Yesterday",
    status: "REVIEWED",
    recommendedAction: "Notify buyer of 21% price divergence from market reference.",
  },
  {
    id: "anom-3",
    type: "DATA_QUALITY",
    severity: "info",
    title: "Duplicate Price Observation Auto-Filtered",
    productName: "Irish Potatoes (Kinigi)",
    location: "Musanze Market",
    detectedDifference: "Identical timestamp entry from API Stream B",
    timestamp: "2 Days Ago",
    status: "RESOLVED",
    recommendedAction: "De-duplicated automatically by data governance pipeline.",
  },
];

export const MOCK_FARMER_DEMAND_SIGNALS: FarmerDemandSignal[] = [
  {
    id: "fds-1",
    cropName: "Plum Tomatoes",
    category: "Horticulture",
    region: "Northern & Eastern",
    targetMonth: "October - November 2026",
    aggregatedMonthlyDemandKg: 24500,
    demandGrowthTrend: "Increasing",
    recommendedPlantingWindow: "Plant by Sept 20 - Harvest early Nov",
    minagriBenchmarkPrice: 1350,
    expectedFarmGatePrice: 1100,
    contractedBuyersCount: 38,
  },
  {
    id: "fds-2",
    cropName: "Kinigi Potatoes",
    category: "Roots & Tubers",
    region: "Musanze & Nyabihu",
    targetMonth: "Continuous (Q4 2026)",
    aggregatedMonthlyDemandKg: 45000,
    demandGrowthTrend: "Stable",
    recommendedPlantingWindow: "Staggered 2-week planting cycles",
    minagriBenchmarkPrice: 520,
    expectedFarmGatePrice: 440,
    contractedBuyersCount: 62,
  },
  {
    id: "fds-3",
    cropName: "Red Onions",
    category: "Vegetables",
    region: "Bugesera & Bugesera Lakes",
    targetMonth: "November - December 2026",
    aggregatedMonthlyDemandKg: 18000,
    demandGrowthTrend: "Increasing",
    recommendedPlantingWindow: "Plant immediately for holiday demand",
    minagriBenchmarkPrice: 980,
    expectedFarmGatePrice: 820,
    contractedBuyersCount: 29,
  },
];

export const MOCK_SUPPLIER_SCORES: SupplierQualityScore[] = [
  {
    supplierId: "sup-1",
    supplierName: "Musanze Potato Farmers Cooperative",
    region: "Northern Province",
    productsSupplied: ["Irish Potatoes (Kinigi)", "Carrots", "Cabbage"],
    fulfillmentReliabilityPct: 98.4,
    freshnessScorePct: 96.0,
    priceCompetitivenessPct: 94.5,
    onTimeDeliveryPct: 97.2,
    overallScore: 96,
    grade: "A+",
  },
  {
    supplierId: "sup-2",
    supplierName: "Kimironko Fresh Traders Group",
    region: "Kigali City",
    productsSupplied: ["Plum Tomatoes", "Red Onions", "Green Peppers"],
    fulfillmentReliabilityPct: 91.2,
    freshnessScorePct: 89.5,
    priceCompetitivenessPct: 92.0,
    onTimeDeliveryPct: 93.0,
    overallScore: 91,
    grade: "A",
  },
  {
    supplierId: "sup-3",
    supplierName: "Nyabugogo Livestock & Meat Distro",
    region: "Kigali City",
    productsSupplied: ["Prime Fresh Beef", "Whole Local Chicken"],
    fulfillmentReliabilityPct: 88.0,
    freshnessScorePct: 92.5,
    priceCompetitivenessPct: 85.0,
    onTimeDeliveryPct: 86.5,
    overallScore: 87,
    grade: "B",
  },
];

export const MOCK_TRACEABILITY_BATCHES: TraceabilityBatch[] = [
  {
    batchId: "FB-BATCH-2026-0982",
    productName: "Plum Tomatoes (Grade A)",
    originFarm: "SunValley Eco Farm",
    district: "Musanze District",
    harvestDate: "2026-09-09 06:00 AM",
    deliveryDate: "2026-09-10 08:30 AM",
    qualityGrade: "Grade A",
    certification: "MINAGRI Verified Organic",
    temperatureLogs: "Maintained 12°C - 14°C cold chain transport",
    qrCodeId: "QR-TOM-982-VERIFIED",
  },
  {
    batchId: "FB-BATCH-2026-0811",
    productName: "Prime Fresh Beef",
    originFarm: "Nyagatare Cattle Ranch Co.",
    district: "Nyagatare District",
    harvestDate: "2026-09-08 04:00 AM",
    deliveryDate: "2026-09-09 07:00 AM",
    qualityGrade: "Premium",
    certification: "Standard GAP",
    temperatureLogs: "Refrigerated transport @ 3°C recorded continuously",
    qrCodeId: "QR-BEEF-811-VERIFIED",
  },
];

export const MOCK_MARKET_REPORTS: MarketReport[] = [
  {
    id: "rep-1",
    title: "MINAGRI Q3 Food Price & Commodity Index Report",
    reportType: "Monthly Benchmark",
    publishedDate: "September 01, 2026",
    periodCovered: "June - August 2026",
    summary: "Comprehensive breakdown of historical prices across 12 major Rwandan agricultural markets, highlighting seasonal tomato dip and grain inflation trends.",
    downloadSize: "2.4 MB PDF",
    featuredProducts: ["Tomatoes", "Irish Potatoes", "Beef", "Rice", "Cooking Oil"],
  },
  {
    id: "rep-2",
    title: "Weekly Kigali Fresh Produce Benchmark Index",
    reportType: "Weekly Index",
    publishedDate: "September 08, 2026",
    periodCovered: "Week 36 (2026)",
    summary: "Daily MINAGRI API aggregation comparing Kimironko, Kicukiro, and Nyabugogo reference prices vs FoodBundles platform procurement quotes.",
    downloadSize: "1.1 MB PDF",
    featuredProducts: ["Tomatoes", "Onions", "Cabbage", "Carrots"],
  },
  {
    id: "rep-3",
    title: "Farmer Supply Outlook & Demand Aggregation Q4",
    reportType: "Farmer Supply Outlook",
    publishedDate: "August 25, 2026",
    periodCovered: "Q4 2026 Forecast",
    summary: "Aggregated restaurant and hotel demand signals transformed into actionable crop planting forecasts for regional farmer cooperatives.",
    downloadSize: "3.8 MB PDF",
    featuredProducts: ["Red Onions", "Kinigi Potatoes", "Beans", "Peppers"],
  },
];
